In [10]:
import numpy as np
import cv2

In [11]:
img = cv2.imread(r'C:\Users\dell\Desktop\Minor_project_facerec\face\1_OpenCV\data\friends.jpg')
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
#Load cascade classifier

haar=cv2.CascadeClassifier(r'C:\Users\dell\Desktop\Minor_project_facerec\face\1_OpenCV\data\haarcascade_frontalface_default.xml')


In [26]:
image = img.copy()
#  step 1: convert image too grayscale

gray_img=cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# cv2.imshow('Gray image', gray_img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# step2: apply grayscale image to cascade classifier
face_rect=haar.detectMultiScale(gray_img,1.3,5)

for x,y,w,h in face_rect:
  cv2.rectangle(image,(x,y),(x+h,y+w),(0,255,0),2)

cv2.imshow('detected faces', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
print(face_rect)

[[216  24  60  60]
 [ 95  29  61  61]
 [158  31  61  61]]


### Real Time Face Detection OpenCV

In [ ]:
cap=cv2.VideoCapture(r'C:\Users\dell\Desktop\Minor_project_facerec\face\1_OpenCV\data\video.mp4')

while True:
    ret, frame = cap.read()
    if ret==False:
        break
    

    
    image = frame.copy()
    #  step 1: convert image too grayscale

    gray_img=cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # cv2.imshow('Gray image', gray_img)
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()

    # step2: apply grayscale image to cascade classifier
    face_rect=haar.detectMultiScale(gray_img,1.3,5)

    for x,y,w,h in face_rect:
      cv2.rectangle(image,(x,y),(x+h,y+w),(0,255,0),2)

    
    cv2.imshow('face detection', image)



    if cv2.waitKey(1)==27:
        break
cap.release()
cv2.destroyAllWindows()    